/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventana;

import java.awt.Color;

import edicionComboBox.EditarComboBox;
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import conectar.Conexion;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author suare
 */
public class AgregarBovinos extends javax.swing.JPanel {

    /**
     * Creates new form AgregarBovinos
     */
    Color color2 = new Color(0, 148, 104);
    int id;

    public AgregarBovinos() {
        initComponents();
        id = Login.iduser;
        setSize(898, 440);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnoarete = new javax.swing.JTextField();
        txtfechanacimiento = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 148, 104));
        jLabel1.setText("Agregar Bovino");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 80));

        txtnoarete.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel1.add(txtnoarete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 240, 30));

        txtfechanacimiento.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        txtfechanacimiento.setText("DD/MM/AAAA");
        txtfechanacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtfechanacimientoMousePressed(evt);
            }
        });
        jPanel1.add(txtfechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 240, 25));

        txtEdad.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 90, 25));

        txtColor.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 90, 25));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Color");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("KG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 265, 110, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Fecha de nacimiento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("No. Arete");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        btnGuardar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login transparente.png"))); // NOI18N
        btnGuardar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, -1));

        btnLimpiar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login transparente.png"))); // NOI18N
        btnLimpiar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 150, -1));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Categoria");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, -1));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ternera", "Vaquilla", "Vaca lechera", "Ternero Macho", "Garote", "Buey", " " }));
        jPanel1.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 120, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Peso");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, -1));

        txtPeso.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 90, 25));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Edad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Meses");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 185, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //boton giuardar
        //recuperar datos
        String noArete, fechaNacimiento, edad, color, peso, categoria = "";
        int bandera = 0, cate = 0;

        noArete = txtnoarete.getText();
        fechaNacimiento = txtfechanacimiento.getText();
        edad = txtEdad.getText();
        color = txtColor.getText();
        cate = cmbCategoria.getSelectedIndex() + 1;
        peso = txtPeso.getText();

        //validar casillas acias
        if (noArete.equals("")) {
            txtnoarete.setBackground(color2);
            bandera++;
        }

        if (fechaNacimiento.equals("")) {
            txtfechanacimiento.setBackground(color2);
            bandera++;
        }

        if (edad.equals("")) {
            txtEdad.setBackground(color2);
            bandera++;
        }

        if (color.equals("")) {
            txtColor.setBackground(color2);
            bandera++;
        }
        if (cate == 1) {
            categoria = "Ternera";

        } else if (cate == 2) {
            categoria = "Vaquilla";
        } else if (cate == 3) {
            categoria = "Vaca lechera";
        } else if (cate == 4) {
            categoria = "Ternero Macho";
        } else if (cate == 5) {
            categoria = "Garote";
        } else if (cate == 6) {
            categoria = "Buey";
        }

        if (bandera == 0) {
            try {
                String arete = txtnoarete.getText();

                Connection cn1 = Conexion.conectar();
                PreparedStatement pst1 = cn1.prepareStatement(
                        "select no_arete from bovinos where no_arete ='" + arete + "'");

                ResultSet rs1 = pst1.executeQuery();
                if (rs1.next()) {

                    JOptionPane.showMessageDialog(null, "El arete ya esta registrado ");
                    cn1.close();

                } else {

                    //conectar a la base de datos
                    try {

                        Connection cn = Conexion.conectar();
                        PreparedStatement pst = cn.prepareStatement(
                                "insert into bovinos value (?,?,?,?,?,?,?,?) ");

                        pst.setString(1, noArete);
                        pst.setInt(2, id);
                        pst.setString(3, fechaNacimiento);
                        pst.setString(4, edad);
                        pst.setString(5, peso);
                        pst.setString(6, color);
                        pst.setString(7, categoria);
                        pst.setString(8, "Activo");

                        pst.executeUpdate();
                        cn.close();

                        txtnoarete.setText("");
                        txtColor.setText("");
                        txtfechanacimiento.setText("DD/MM/AAAA");
                        txtEdad.setText("");
                        txtPeso.setText("");

                        JOptionPane.showMessageDialog(null, "Resgitro exitoso");
                        cn.close();

                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Error al guardar bovino nuevo");
                        System.err.println("Error al guardadar nuevo bovino " + e);
                    }

                }
            } catch (SQLException e) {

                JOptionPane.showMessageDialog(null, "Error al comparar codigo de barras");
                System.err.println("error al comparar cod de barras " + e);
            }

        } else {

            JOptionPane.showMessageDialog(null, "Debe de llenr todo los datos");
            System.err.println("No lleno todo los datos ");
            txtColor.setBackground(Color.WHITE);
            txtnoarete.setBackground(Color.WHITE);
            txtfechanacimiento.setBackground(Color.WHITE);
            txtEdad.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtfechanacimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfechanacimientoMousePressed
        txtfechanacimiento.setText("");
    }//GEN-LAST:event_txtfechanacimientoMousePressed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtnoarete.setText("");
        txtColor.setText("");
        txtfechanacimiento.setText("DD/MM/AAAA");
        txtEdad.setText("");
        txtPeso.setText("");

    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtfechanacimiento;
    private javax.swing.JTextField txtnoarete;
    // End of variables declaration//GEN-END:variables
}
