/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventana;

import java.sql.*;
import conectar.Conexion;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author suare
 */
public class BuscarBovino extends javax.swing.JPanel {

    /**
     * Creates new form BuscarBovino
     */
    Color color2 = new Color(0, 148, 104);

    public BuscarBovino() {
        initComponents();
        setSize(898, 440);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnoarete = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JLabel();
        txtfechnacimiento = new javax.swing.JLabel();
        txtEdad = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtestsdo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 148, 104));
        jLabel1.setText("Buscar Bovino");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 80));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("No. Arete");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        txtnoarete.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel1.add(txtnoarete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 240, 30));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Fecha de nacimiento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Edad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Meses");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 185, 110, -1));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Color");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Peso");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("KG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 265, 110, -1));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Categoria");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, -1));

        txtcategoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 90, 30));

        txtfechnacimiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtfechnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 240, 30));

        txtEdad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 90, 30));

        txtColor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 90, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_search_24px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 88, 30, 30));

        txtPeso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 90, 30));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Estado");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, -1));

        txtestsdo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtestsdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        //buscar Bovinos
        String arete = txtnoarete.getText();

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from bovinos where no_arete ='" + arete + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                txtfechnacimiento.setText(rs.getString("fecha_nac_bov"));
                txtEdad.setText(rs.getString("edad"));
                txtColor.setText(rs.getString("color"));
                txtPeso.setText(rs.getString("peso"));
                txtcategoria.setText(rs.getString("raza"));
                txtestsdo.setText(rs.getString("estadobov"));
                cn.close();

            } else {
                JOptionPane.showMessageDialog(null, "El arete no esta registrado ");
            }

        } catch (SQLException e) {

            System.err.println("Error al buscar bovino " +e);
            JOptionPane.showMessageDialog(null, "Error al buscar bovino");
        }
    }//GEN-LAST:event_jLabel11MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtColor;
    private javax.swing.JLabel txtEdad;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtcategoria;
    private javax.swing.JLabel txtestsdo;
    private javax.swing.JLabel txtfechnacimiento;
    private javax.swing.JTextField txtnoarete;
    // End of variables declaration//GEN-END:variables
}
