/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventana;

import java.sql.*;
import conectar.Conexion;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
/**
 *
 * @author suare
 */
public class EliminarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form EliminarUsuario
     */
    Color color2 = new Color(0, 148, 104);
    public EliminarUsuario() {
        initComponents();
           setSize(920, 440);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        txtnombre = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login.png"))); // NOI18N
        btnGuardar.setText("Eliminar");
        btnGuardar.setBorder(null);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login transparente.png"))); // NOI18N
        btnGuardar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 150, -1));

        txtnombre.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtnombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 240, 30));

        txtid.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 240, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_search_24px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 30, 30));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("ID usuario");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 148, 104));
        jLabel1.setText("Eliminar usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String empleado;
        empleado = txtid.getText();

        //abrir conexion para eliminar empleado
        if (!empleado.equals("")) {

            try {

                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                    "delete from usuarios where idusuarios =?");

                pst.setString(1, empleado);
                pst.executeUpdate();

                txtid.setText("");
                txtnombre.setText("");
                JOptionPane.showMessageDialog(null, "El usuario se elimino");

            } catch (SQLException e) {

                JOptionPane.showMessageDialog(null, "Error al eliminar usuario");
                System.err.println("Error al eliminar empleado " + e);
            }
        } else {

            JOptionPane.showMessageDialog(null, "Ingrese el id del usuario");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        //verificar que no este vacia la casilla de id trabajador
        String idtrabajador;
        idtrabajador = txtid.getText();

        if (!idtrabajador.equals("")) {

            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst =cn.prepareStatement(
                    "select nombre_us,apellidoP_us,apellidoM_us from usuarios where idusuarios='" + idtrabajador+"'");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {

                    String nom = rs.getString("nombre_us");
                    String app =rs.getString("apellidoP_us");
                    String apm = rs.getString("apellidoM_us");

                    String nombre = nom + " " + app+ " " + apm;
                    txtnombre.setText(nombre);

                    cn.close();
                } else {

                    JOptionPane.showMessageDialog(null, "El trabajador no existe");
                    cn.close();
                }

            } catch (SQLException e) {
                System.err.println("Error al consultar datos " + e);
                JOptionPane.showMessageDialog(null, "Error al Buscar trabajador");
            }

        }else{
            txtid.setBackground(color2);

            JOptionPane.showMessageDialog(null,"Ingrese el id del trabajador");
            txtid.setBackground(Color.white);
        }
    }//GEN-LAST:event_jLabel11MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtid;
    private javax.swing.JLabel txtnombre;
    // End of variables declaration//GEN-END:variables
}
