/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import java.awt.Color;
import javax.swing.JOptionPane;
import conectar.Conexion;
import java.sql.*;
import javax.crypto.AEADBadTagException;

/**
 *
 * @author suare
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int xMouse, yMouse;

    public static String usuario;//para compartir  el nombre de usuario con las demas interfaces
    public static String nombreusuario;
    public static int iduser;//compartir id 

    public Login() {
        initComponents();
        setSize(1067, 621);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_login = new javax.swing.JPanel();
        btn_minimizar = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        BoviControl = new javax.swing.JLabel();
        jlabelnombreUsuario = new javax.swing.JTextField();
        jlabelcontraseñaUsuario = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btn_entrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_login.setBackground(new java.awt.Color(255, 255, 255));
        panel_login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_loginMouseDragged(evt);
            }
        });
        panel_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_loginMousePressed(evt);
            }
        });
        panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimizar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btn_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadro_blanco.png"))); // NOI18N
        btn_minimizar.setText("_");
        btn_minimizar.setBorder(null);
        btn_minimizar.setFocusPainted(false);
        btn_minimizar.setFocusable(false);
        btn_minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_minimizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadro_blanco.png"))); // NOI18N
        btn_minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadro_verde.png"))); // NOI18N
        btn_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizarActionPerformed(evt);
            }
        });
        panel_login.add(btn_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 30, 30));

        btn_cerrar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadro_blanco.png"))); // NOI18N
        btn_cerrar.setText("X");
        btn_cerrar.setBorder(null);
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setFocusable(false);
        btn_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadro_blanco.png"))); // NOI18N
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadro_verde.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        panel_login.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 30));

        BoviControl.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        BoviControl.setForeground(new java.awt.Color(0, 148, 104));
        BoviControl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoviControl.setText("BoviControl");
        panel_login.add(BoviControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 90));

        jlabelnombreUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jlabelnombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jlabelnombreUsuario.setText("Usuario");
        jlabelnombreUsuario.setCaretColor(new java.awt.Color(204, 204, 204));
        jlabelnombreUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlabelnombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlabelnombreUsuarioMousePressed(evt);
            }
        });
        panel_login.add(jlabelnombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 170, 220, 25));

        jlabelcontraseñaUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jlabelcontraseñaUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jlabelcontraseñaUsuario.setText("contraseña");
        jlabelcontraseñaUsuario.setCaretColor(new java.awt.Color(204, 204, 204));
        jlabelcontraseñaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlabelcontraseñaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlabelcontraseñaUsuarioMousePressed(evt);
            }
        });
        panel_login.add(jlabelcontraseñaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 220, 220, 25));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 148, 104));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INICIAR SECION");
        panel_login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 620, -1));

        btn_entrar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login.png"))); // NOI18N
        btn_entrar.setText("Entrar");
        btn_entrar.setBorder(null);
        btn_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_entrar.setFocusPainted(false);
        btn_entrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_entrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login.png"))); // NOI18N
        btn_entrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton login transparente.png"))); // NOI18N
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        panel_login.add(btn_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_password_30px.png"))); // NOI18N
        panel_login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 218, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_user_male_30px.png"))); // NOI18N
        panel_login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 167, 30, 30));

        getContentPane().add(panel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 620, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen principal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlabelnombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelnombreUsuarioMousePressed

        jlabelnombreUsuario.setText("");
        jlabelnombreUsuario.setForeground(Color.black);
        jlabelnombreUsuario.setBackground(Color.white);
        jlabelcontraseñaUsuario.setBackground(Color.white);
        String contraseñaUsuario = jlabelcontraseñaUsuario.getText();

        if (contraseñaUsuario.equals("")) {
            jlabelcontraseñaUsuario.setText("Contraseña");

        }


    }//GEN-LAST:event_jlabelnombreUsuarioMousePressed

    private void jlabelcontraseñaUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelcontraseñaUsuarioMousePressed

        jlabelcontraseñaUsuario.setText("");
        jlabelcontraseñaUsuario.setForeground(Color.black);

        jlabelnombreUsuario.setBackground(Color.white);
        jlabelcontraseñaUsuario.setBackground(Color.white);
        String nomUsuario = jlabelnombreUsuario.getText();

        if (nomUsuario.equals("")) {

            jlabelnombreUsuario.setText("Usuario");

        }
    }//GEN-LAST:event_jlabelcontraseñaUsuarioMousePressed

    private void panel_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_loginMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_loginMousePressed

    private void panel_loginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_loginMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);


    }//GEN-LAST:event_panel_loginMouseDragged

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizarActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_btn_minimizarActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed

        //recuperar datos 
        String pass;
        int validacion = 0;

        usuario = jlabelnombreUsuario.getText();
        pass = jlabelcontraseñaUsuario.getText();

        if (usuario.equals("")) {
            jlabelnombreUsuario.setBackground(Color.getHSBColor(198, 243, 221));
            validacion++;
        }
        if (pass.equals("")) {
            jlabelcontraseñaUsuario.setBackground(Color.getHSBColor(198, 243, 221));
            validacion++;
        }

        if (validacion == 0) {
            //establecer conexion xon la base de datos

            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("select nombre_us, username, idusuarios, tipo_us, estado from usuarios "
                        + "where username ='" + usuario + "' and password_us = '" + pass + "'");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {

                    iduser = rs.getInt("idusuarios");//recuperar id de usuario para compartir
                    nombreusuario = rs.getString("nombre_us");
                    usuario = rs.getString("username");
                    String estado = rs.getString("estado");//recuperar el estado de usuario
                    String tipoUsuario = rs.getString("tipo_us");//recupera el nivel de usuario
                    
                    if (estado.equalsIgnoreCase("Activo") && tipoUsuario.equalsIgnoreCase("Administrador")) {
                        
                        MenuAdministrador menuAdministrador = new MenuAdministrador();
                        menuAdministrador.setVisible(true);//abrir el jframe de menu del administrador
                        dispose();
                        cn.close();//cerrar la conexion a la base de datos
                        
                    }else if (estado.equalsIgnoreCase("Activo") && tipoUsuario.equalsIgnoreCase("Capturista")) {
                        
                        MenuCapturista menucapturista = new MenuCapturista();
                        menucapturista.setVisible(true);//abrir el jframe de menu del capturista
                        dispose();
                        cn.close();//cerrar la conexion a la base de datos
                    }

                } else {
                    cn.close();
                    if (!usuario.equals("Usuario") && !pass.equals("cotraseña")) {
                        JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto");
                        jlabelnombreUsuario.setText("Usuario");
                        jlabelcontraseñaUsuario.setText("Contrraseña");
                    }

                }
            } catch (SQLException e) {

                JOptionPane.showMessageDialog(null, "Error al consultar los datos ");
                System.err.println("error al consultar datos en el login " + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe de llenar todo los campos");
        }

    }//GEN-LAST:event_btn_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoviControl;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_minimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jlabelcontraseñaUsuario;
    private javax.swing.JTextField jlabelnombreUsuario;
    private javax.swing.JPanel panel_login;
    // End of variables declaration//GEN-END:variables
}
